package com.luv2code.springboot.thymeleafdemo.dao;

import org.springframework.data.jpa.repository.JpaRepository;

import com.luv2code.springboot.thymeleafdemo.entity.Employee;

import java.util.List;

public interface EmployeeRepository extends JpaRepository<Employee, Integer> {
    //add method to sort by last name
    //Spring Data JPA will parse the method name
    //and create the query for you
    public List<Employee> findAllByOrderByLastNameAsc();

	// that's it ... no need to write any code LOL!

    //Resful APIs generated by Spring Data JPA
    //provide CRUD operations for free
    //no need to write any code LOL!
    //like this:
    //http://localhost:8080/employees save , update , delete , get all
    //http://localhost:8080/employees/1 , deleteById
    //http://localhost:8080/employees/2
	
}
